### ISSUE TITLE
Lint-on-save not working

### ISSUE THREAD

**Issue by mrmurphy** [mybuddymichael/linter-elm-make#36] opened 2016-06-07 01:36 UTC
@halohalospecial I didn't test this before merging the lint-on-the-fly PR, but when I save the file, the lint results disappear. I have to make an edit before they show up again.

I turned on the setting 'Only lint on save' to test and that makes the lint results (the inline markings in the editor) disappear entirely, never showing up at all. Any ideas?

Thanks, again! @mybuddymichael do you think you could add @halohalospecial to the repo, too to make publishing easier?

**Comment by halohalospecial** [comment] 2016-06-07 02:16
I'll test it later when I get back. It's maybe because of my last minute changes, sorry.

**Comment by mrmurphy** [comment] 2016-06-07 02:20
No problem. Thank you!

**Comment by halohalospecial** [comment] 2016-06-07 04:41
Hmm, I couldn't reproduce the behavior you mentioned.  Can you give me a sample file? Thanks.

**Comment by mybuddymichael** [comment] 2016-06-07 04:42
@halohalospecial I just added you as a collaborator on the repo. Thanks for your contributions and help!

**Comment by halohalospecial** [comment] 2016-06-07 04:53
Wow, thanks! :)

**Comment by halohalospecial** [comment] 2016-06-07 06:31
@splodingsocks, in the `linter` package settings, was the `Lint As You Type` option checked?  When I unchecked mine, the behavior was similar to what you described.

**Comment by mrmurphy** [comment] 2016-06-08 10:48
@halohalospecial hmm, I have my "Lint As You Type" checked for the Linter package. I'll see if it happens with a basic project.

**Comment by mrmurphy** [comment] 2016-06-08 11:13
@halohalospecial I just reproduced in a new project with the following contents:

# Main.elm

``` elm
module Main exposing (..)


foo : String
foo =
    1
```

# elm-package.json

``` elm
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.1 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

Running `linter-elm-make@0.6.0`, `linter@1.11.4, and Atom 1.7.4.

I'm upgrading Atom now to 1.9 beta to see if that has anything to do with it.

**Comment by halohalospecial** [comment] 2016-06-09 01:05
@splodingsocks on-the-fly linting worked for the example you gave.  I'm running linter-elm-make@0.7.1, linter@1.11.5, Atom 1.8.0 and Ubuntu 16.04.  It also worked on OS X El Capitan before.  Maybe a conflict with some other package or Linter setting in your machine? I even tried deleting my ~/.atom directory and just installed `linter`, `language-elm`, and `linter-elm-make`.

**Comment by halohalospecial** [comment] 2016-06-16 08:32
@splodingsocks maybe you can try the latest release.  The 0.6.0 release has various non-obvious bugs :)

**Comment by mrmurphy** [comment] 2016-06-16 15:20
Definitely. @halohalospecial did you already publish it? I've been waiting for the notification of an available upgrade, but haven't gotten one. Or maybe I'm still pointing to my local copy. I'll check that.

**Comment by mrmurphy** [comment] 2016-06-16 15:21
@halohalospecial Oh wow, yeah, I was behind. Installing 0.9.0 now.

**Comment by halohalospecial** [comment] 2016-06-17 03:00
@splodingsocks if there are no `Lint On The Fly` and `Report Warnings` options in config, you may need to reinstall the package and restart Atom.  The changes in the config options sometimes do not show up if you just upgrade.  I don't know how to solve it yet :(

**Comment by halohalospecial** [comment] 2016-07-12 01:18
Closing this since we already know that the issue is related to `elm-format`.  See https://github.com/mybuddymichael/linter-elm-make/issues/55

**Closed as completed by halohalospecial** 2016-07-12 01:18 UTC
